workflows:
  ios-release:
    name: iOS App Store Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Initialize keychain
        script: keychain initialize
      - name: Generate private key and fetch signing files
        script: |
          CERT_KEY=$(openssl genrsa 2048 2>/dev/null)
          app-store-connect fetch-signing-files com.enginkeskin.bollinger \
            --type IOS_APP_STORE \
            --certificate-key "$CERT_KEY" \
            --create
      - name: Add certificates to keychain
        script: keychain add-certificates
      - name: Set up code signing
        script: xcode-project use-profiles
      - name: Build IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
