workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files com.enginkeskin.bollinger \
            --type IOS_APP_STORE \
            --create
      - name: Use profiles
        script: |
          keychain initialize
          app-store-connect certificates list \
            --type APPLE_DISTRIBUTION \
            --certificate-key=@env:CM_CERTIFICATE_PRIVATE_KEY \
            --save || \
          app-store-connect certificates create \
            --type APPLE_DISTRIBUTION \
            --certificate-key=@env:CM_CERTIFICATE_PRIVATE_KEY \
            --save
          app-store-connect profiles list \
            --type IOS_APP_STORE \
            --bundle-id com.enginkeskin.bollinger \
            --save || \
          app-store-connect profiles create \
            --type IOS_APP_STORE \
            --bundle-id com.enginkeskin.bollinger \
            --save
          keychain add-certificates
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Build IPA
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$(($(app-store-connect get-latest-testflight-build-number "com.enginkeskin.bollinger" || echo 0) + 1)) \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - External Testers
